### ISSUE TITLE
String comparisons

### ISSUE THREAD

**Issue by OndrejMarsalek** [fuulish/surf#4]
With Clang, I get warnings like the following from `io.c` for many (all?) keywords.

```
/home/marsalek/code/surf/src/io.c:324:37: warning: result of comparison against a string literal is unspecified (use strncmp instead)
      [-Wstring-compare]
            else if ((keywords[key] == "refmask"))
                                    ^  ~~~~~~~~~
/home/marsalek/code/surf/src/io.c:324:37: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
            else if ((keywords[key] == "refmask"))
                      ~~~~~~~~~~~~~~^~~~~~~~~~~~
/home/marsalek/code/surf/src/io.c:324:37: note: remove extraneous parentheses around the comparison to silence this warning
            else if ((keywords[key] == "refmask"))
                     ~              ^           ~
/home/marsalek/code/surf/src/io.c:324:37: note: use '=' to turn this equality comparison into an assignment
            else if ((keywords[key] == "refmask"))
                                    ^~
                                    =
```

**Comment by fuulish** [comment]
Oui, mon cher. Tu peux reparer, si tu veux. 

if( strcmp( keywords[key], "refmask" ) == 0 ) {
}

would be a way to go.

The other variant works, because the pointer comparison that the program is doing is valid. The string literals, like "refmask", only exists once, and have the address that the array keywords[key] holds. If you want to make it nicer (safer?) feel free to change it.

**Comment by OndrejMarsalek** [comment]
Yeah, I realize that "patches welcome" is the default :-) I just thought I'd leave a note of it here until one of the people involved has enough time/focus/mood to actually do it.

Interesting note about string literals, although it is not clear to me if/how that can be guaranteed for strings that are only determined at run time based on data read from a file. Couldn't those be allocated separately? And is it part of the standard, or an implementation detail?

**Comment by OndrejMarsalek** [comment]
If I wanted to phrase it as a complaint, I would tag it as a bug and assign it to you :-p

**Comment by fuulish** [comment]
Sure, and I just wanted to train my French :)

I wanted to check whether that's in the standard or not. I am not sure, TBH.

The safe choice is doing the string comparison using strcmp or strncmp.
